insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (900, 'APP应用进程数检查警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"APP应用进程数检查");' , char(10) , ' long count = Long.valueOf($COUNT[0]); ' , char(10) , '' , char(10) , ' if(count<=4){' , char(10) , '   result.setWarn("BOSS严重告警信息:主机"+$HOST+"("+$IP+"),APP应用进程数已经小于20%,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }' , char(10) , ' else if(count<10){' , char(10) , '   result.setWarn("BOSS普通告警信息:主机"+$HOST+"("+$IP+"),APP应用进程数已经小于50%,发生时间:"+result.getTime()+",请尽快处理!"); ' , char(10) , '   result.setLevel(2);' , char(10) , ' }' , char(10) , ' else if(count<15){' , char(10) , '   result.setWarn("BOSS一般告警信息:主机"+$HOST+"("+$IP+"),APP应用进程数已经小于80%,发生时间:"+result.getTime()+",请尽快处理!");' , char(10) , '   result.setLevel(1);' , char(10) , ' } else {' , char(10) , '    result.setWarn("");' , char(10) , '    result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (500, '进程检查警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , 'result.setName("主机"+$HOST+"进程检查");' , char(10) , ' long flag = Long.valueOf($EXISTFLAG[0]);' , char(10) , ' if(flag<=0){' , char(10) , '   result.setWarn("BOSS严重告警信息:"+$NAME[0]+"不存在,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (1000, '接口的端口数不等于1警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"接口的端口数量检查");' , char(10) , ' long count = Long.valueOf($COUNT[0]); ' , char(10) , '' , char(10) , ' if(count != 1){' , char(10) , '   result.setWarn("BOSS严重告警信息:"+$INFO_NAME+",接口的端口数量"+count+"不是1个,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' } else {' , char(10) , '    result.setWarn("");' , char(10) , '    result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (1100, '接口的端口数小于2警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"接口的端口数量检查");' , char(10) , ' long count = Long.valueOf($COUNT[0]); ' , char(10) , '' , char(10) , ' if(count<2){' , char(10) , '   result.setWarn("BOSS严重告警信息:"+$INFO_NAME+",接口的端口数量"+count+"已经小于2个,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' } else {' , char(10) , '    result.setWarn("");' , char(10) , '    result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (1200, '接口的端口数小于4警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"接口的端口数量检查");' , char(10) , ' long count = Long.valueOf($COUNT[0]); ' , char(10) , '' , char(10) , ' if(count<4){' , char(10) , '   result.setWarn("BOSS严重告警信息:"+$INFO_NAME+",接口的端口数量"+count+"已经小于4个,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' } else {' , char(10) , '    result.setWarn("");' , char(10) , '    result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (3300, '表积压监控警告_上发计费接口表', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("表错误监控");' , char(10) , ' long count = Long.valueOf($LC[0]);' , char(10) , ' if(count>1000){' , char(10) , '   result.setWarn("BOSS严重告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else if (count>100){' , char(10) , '   result.setWarn("BOSS普通告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(2);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (1300, '接口的端口数小于6警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"接口的端口数量检查");' , char(10) , ' long count = Long.valueOf($COUNT[0]); ' , char(10) , '' , char(10) , ' if(count<6){' , char(10) , '   result.setWarn("BOSS严重告警信息:"+$INFO_NAME+",接口的端口数量"+count+"已经小于6个,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' } else {' , char(10) , '    result.setWarn("");' , char(10) , '    result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (1400, '接口的端口数小于10警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"ATMI接口的端口数量检查");' , char(10) , ' long count = Long.valueOf($COUNT[0]); ' , char(10) , '' , char(10) , ' if(count<10){' , char(10) , '   result.setWarn("BOSS严重告警信息:"+$INFO_NAME+",接口的端口数量"+count+"已经小于10个,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' } else {' , char(10) , '    result.setWarn("");' , char(10) , '    result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (1500, 'app文件系统使用率警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , 'result.setName("主机"+$HOST+"文件系统使用率");' , char(10) , '' , char(10) , ' long percent = Long.valueOf($FS[0]);' , char(10) , ' if(percent>=90){' , char(10) , '   result.setWarn("BOSS严重告警信息:主机"+$HOST+"("+$IP+"),/app文件系统目前使用率已经达到"+percent+"%,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else if(percent>=80){' , char(10) , '   result.setWarn("BOSS普通告警信息:主机"+$HOST+"("+$IP+"),/app文件系统目前使用率已经达到"+percent+"%,发生时间:"+result.getTime()+",请尽快处理!"); ' , char(10) , '   result.setLevel(2);' , char(10) , ' }' , char(10) , ' else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (1600, 'data文件系统使用率警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , 'result.setName("主机"+$HOST+"文件系统使用率");' , char(10) , '' , char(10) , ' long percent = Long.valueOf($FS[0]);' , char(10) , ' if(percent>=90){' , char(10) , '   result.setWarn("BOSS严重告警信息:主机"+$HOST+"("+$IP+"),/data文件系统目前使用率已经达到"+percent+"%,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else if(percent>=80){' , char(10) , '   result.setWarn("BOSS普通告警信息:主机"+$HOST+"("+$IP+"),/data文件系统目前使用率已经达到"+percent+"%,发生时间:"+result.getTime()+",请尽快处理!"); ' , char(10) , '   result.setLevel(2);' , char(10) , ' }' , char(10) , ' else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (3400, '调度表积压监控警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("表错误监控");' , char(10) , ' long count = Long.valueOf($LC[0]);' , char(10) , ' if(count>100){' , char(10) , '   result.setWarn("RBOSS调度严重告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else if (count>50){' , char(10) , '   result.setWarn("RBOSS调度普通告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(2);' , char(10) , ' }else if (count>10){' , char(10) , '   result.setWarn("RBOSS调度轻微告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(1);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (4000, '表错误监控警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("表错误监控");' , char(10) , ' long count = Long.valueOf($LC[0]);' , char(10) , ' if(count>2000){' , char(10) , '   result.setWarn("BOSS严重告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else if (count>1500){' , char(10) , '   result.setWarn("BOSS普通告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(2);' , char(10) , ' }else if (count>1000){' , char(10) , '   result.setWarn("BOSS轻微告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(1);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (4100, '表积压监控警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("表错误监控");' , char(10) , ' long count = Long.valueOf($LC[0]);' , char(10) , ' if(count>5000){' , char(10) , '   result.setWarn("BOSS严重告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else if (count>2000){' , char(10) , '   result.setWarn("BOSS普通告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(2);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (501, 'CPU告警', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"CPU使用率");' , char(10) , ' long cpu_used_percent = Long.valueOf($CPU_USED_PERCENT[0]);' , char(10) , '' , char(10) , ' if(cpu_used_percent>=95){' , char(10) , '   result.setWarn("BOSS严重告警信息:主机"+$HOST+"("+$IP+"),cpu使用率已经大于"+cpu_used_percent+"%,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }' , char(10) , ' else if(cpu_used_percent>=80){' , char(10) , '   result.setWarn("BOSS普通告警信息:主机"+$HOST+"("+$IP+"),cpu使用率已经大于"+cpu_used_percent+"%,发生时间:"+result.getTime()+",请尽快处理!"); ' , char(10) , '   result.setLevel(2);' , char(10) , ' }' , char(10) , ' else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (504, '测试内存使用率警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"内存使用率");' , char(10) , ' long mem_used_percent = Long.valueOf($MEM_USED_PERCENT[0]); ' , char(10) , '' , char(10) , ' if(mem_used_percent>=97){' , char(10) , '   result.setWarn("BOSS严重告警信息:主机"+$HOST+"("+$IP+"),内存使用率已经大于"+mem_used_percent+"%,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }' , char(10) , ' else if(mem_used_percent>=80){' , char(10) , '   result.setWarn("BOSS普通告警信息:主机"+$HOST+"("+$IP+"),内存使用率已经大于"+mem_used_percent+"%,发生时间:"+result.getTime()+",请尽快处理!"); ' , char(10) , '   result.setLevel(2);' , char(10) , ' }' , char(10) , ' else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (524, 'aa', 'aav', null, null, null, null, 0, 'E', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (502, 'sdasdasdsadsad', concat('aasdsadsadsad' , char(10) , 'asddddddddddddddddddddddd' , char(10) , 'asdddddddddddddddddddddddddddddddddddddddd' , char(10) , 'asdddddddddddddddddd'), null, null, null, null, 0, 'E', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (503, 'aaaaaaaaaaaaaaaaaa', concat('aaaaaaaaaaaaaa' , char(10) , 'aaaaaaaaaaaaaaaaaaaaa                  aaaaaaaaaaaaaaaaaa' , char(10) , 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'), null, null, null, null, 0, 'E', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (600, 'Linux主机磁盘IO使用率', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , '  TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , '  result.setName("主机"+$HOST+"磁盘IO使用率");' , char(10) , '' , char(10) , '  String ioUseInfo = String.valueOf($IO_USED_PERCENT[0]);' , char(10) , '  String[] ioInfoArr = ioUseInfo.split("@");' , char(10) , '' , char(10) , '  if(ioInfoArr != null  ioInfoArr.length != 0){' , char(10) , '    for(int i=0;i<ioInfoArr.length;i++){' , char(10) , '     String[] tmpIO = ioInfoArr[i].split("~");' , char(10) , '     long count = Long.valueOf(tmpIO[1]);' , char(10) , '     if(count>=9000){' , char(10) , '    long tmpCount = (count/100);' , char(10) , '    result.setWarn("BOSS严重告警信息:主机"+$HOST+"("+$IP+"),磁盘"+tmpIO[0]+"使用率已经大于"+tmpCount+"%,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '    result.setLevel(3);' , char(10) , '     }else if(count>=8500){' , char(10) , '    long tmpCount = (count/100);' , char(10) , '    result.setWarn("BOSS普通告警信息:主机"+$HOST+"("+$IP+"),磁盘"+tmpIO[0]+"使用率已经大于"+tmpCount+"%,发生时间:"+result.getTime()+",请尽快处理!");' , char(10) , '       result.setLevel(2);' , char(10) , '     }else{' , char(10) , '       result.setWarn("");' , char(10) , '       result.setLevel(0);' , char(10) , '     }' , char(10) , '    }' , char(10) , '  }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (3500, '预缴分摊过程任务处理监控警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("预缴分摊过程任务处理监控");' , char(10) , ' long count = Long.valueOf($LC[0]);' , char(10) , ' if(count != 5){' , char(10) , '   result.setWarn("预缴分摊过程任务处理失败,当前成功的任务个数为"+count+",小于正常的任务个数5个，时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (3600, '预缴充值任务处理监控警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("预缴充值任务处理监控");' , char(10) , ' long count = Long.valueOf($LC[0]);' , char(10) , ' if(count != 3){' , char(10) , '   result.setWarn("预缴充值任务处理失败,当前成功的任务个数为"+count+",小于正常的任务个数3个，时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (3700, '预缴分摊处理异常数据监控警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("预缴分摊处理异常数据监控");' , char(10) , ' long count = Long.valueOf($LC[0]);' , char(10) , ' if(count >= 100){' , char(10) , '   result.setWarn("预缴分摊处理异常,异常条数:"+count+",时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (3100, '表错误监控警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("表错误监控");' , char(10) , ' long count = Long.valueOf($LC[0]);' , char(10) , ' if(count>500){' , char(10) , '   result.setWarn("BOSS严重告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else if (count>350){' , char(10) , '   result.setWarn("BOSS普通告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(2);' , char(10) , ' }else if (count>300){' , char(10) , '   result.setWarn("BOSS轻微告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(1);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (3200, '表积压监控警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("表错误监控");' , char(10) , ' long count = Long.valueOf($LC[0]);' , char(10) , ' if(count>5000){' , char(10) , '   result.setWarn("BOSS严重告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else if (count>3000){' , char(10) , '   result.setWarn("BOSS普通告警信息:("+$INFO_NAME+"),存在数据积压"+count+"条,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(2);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (1, 'CPU使用率警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"CPU使用率");' , char(10) , ' long cpu_used_percent = Long.valueOf($CPU_USED_PERCENT[0]);' , char(10) , '' , char(10) , ' if(cpu_used_percent>=95){' , char(10) , '   result.setWarn("BOSS严重告警信息:主机"+$HOST+"("+$IP+"),cpu使用率已经大于"+cpu_used_percent+"%,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }' , char(10) , ' else if(cpu_used_percent>=80){' , char(10) , '   result.setWarn("BOSS普通告警信息:主机"+$HOST+"("+$IP+"),cpu使用率已经大于"+cpu_used_percent+"%,发生时间:"+result.getTime()+",请尽快处理!"); ' , char(10) , '   result.setLevel(2);' , char(10) , ' }' , char(10) , ' else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (2, '内存使用率警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"内存使用率");' , char(10) , ' long mem_used_percent = Long.valueOf($MEM_USED_PERCENT[0]); ' , char(10) , '' , char(10) , ' if(mem_used_percent>=97){' , char(10) , '   result.setWarn("BOSS严重告警信息:主机"+$HOST+"("+$IP+"),内存使用率已经大于"+mem_used_percent+"%,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }' , char(10) , ' else if(mem_used_percent>=95){' , char(10) , '   result.setWarn("BOSS普通告警信息:主机"+$HOST+"("+$IP+"),内存使用率已经大于"+mem_used_percent+"%,发生时间:"+result.getTime()+",请尽快处理!"); ' , char(10) , '   result.setLevel(2);' , char(10) , ' }' , char(10) , ' else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (3, '文件系统使用率警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , 'result.setName("主机"+$HOST+"文件系统使用率");' , char(10) , '' , char(10) , ' long percent = Long.valueOf($FS[0]);' , char(10) , ' if(percent>=90){' , char(10) , '   result.setWarn("BOSS严重告警信息:主机"+$HOST+"("+$IP+"),文件系统目前使用率已经达到"+percent+"%,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else if(percent>=80){' , char(10) , '   result.setWarn("BOSS普通告警信息:主机"+$HOST+"("+$IP+"),文件系统目前使用率已经达到"+percent+"%,发生时间:"+result.getTime()+",请尽快处理!"); ' , char(10) , '   result.setLevel(2);' , char(10) , ' }' , char(10) , ' else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (400, '端口监控警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , ' TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"端口检查");' , char(10) , ' long flag = Long.valueOf($EXISTFLAG[0]);' , char(10) , ' if(flag<=0){' , char(10) , '   result.setWarn("BOSS严重告警信息:"+$NAME[0]+"不存在,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }else{' , char(10) , '   result.setWarn("");' , char(10) , '   result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
insert into AI_MON_P_THRESHOLD (threshold_id, threshold_name, expr1, expr2, expr3, expr4, expr5, expiry_days, state, remarks)
values (700, 'WEB应用进程数检查警告', concat('import com.asiainfo.monitor.tools.exe.task.model.TaskRtn;' , char(10) , 'TaskRtn result =(TaskRtn)$TASKRTN;' , char(10) , ' result.setName("主机"+$HOST+"WEB应用进程数检查");' , char(10) , ' long count = Long.valueOf($COUNT[0]); ' , char(10) , '' , char(10) , ' if(count<=2){' , char(10) , '   result.setWarn("BOSS严重告警信息:主机"+$HOST+"("+$IP+"),WEB应用进程数已经小于20%,发生时间:"+result.getTime()+",请迅速处理!");' , char(10) , '   result.setLevel(3);' , char(10) , ' }' , char(10) , ' else if(count<5){' , char(10) , '   result.setWarn("BOSS普通告警信息:主机"+$HOST+"("+$IP+"),WEB应用进程数已经小于50%,发生时间:"+result.getTime()+",请尽快处理!"); ' , char(10) , '   result.setLevel(2);' , char(10) , ' }' , char(10) , ' else if(count<7){' , char(10) , '   result.setWarn("BOSS一般告警信息:主机"+$HOST+"("+$IP+"),WEB应用进程数已经小于80%,发生时间:"+result.getTime()+",请尽快处理!");' , char(10) , '   result.setLevel(1);' , char(10) , ' } else {' , char(10) , '    result.setWarn("");' , char(10) , '    result.setLevel(0);' , char(10) , ' }'), null, null, null, null, 0, 'U', null);
commit;