insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (400, 'Linux系统网络流量统计', 'SHELL', concat('#!/bin/sh' , char(10) , '' , char(10) , 'NIC_INFO=`ifconfig | grep ''eth[0-9]'' | awk ''{print $1}''`' , char(10) , '' , char(10) , 'for temp in $NIC_INFO' , char(10) , 'do' , char(10) , '  RECEIVE=`cat /proc/net/dev | grep ${temp} | awk ''{print $2}'' | sed -s ''s/${temp}://g''`' , char(10) , '  SMSSENDER=`cat /proc/net/dev | grep ${temp} | awk ''{print $10}''`' , char(10) , '' , char(10) , '  RECEIVE_CNT=`expr $RECEIVE / 1024`' , char(10) , '  SEND_CNT=`expr  $SMSSENDER / 1024`' , char(10) , '' , char(10) , '  NIC_USED=${NIC_USED}@${temp}-"RECEIVE"~${RECEIVE_CNT}"& SMSSENDER"~${SEND_CNT}' , char(10) , '' , char(10) , 'done' , char(10) , '' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}网络流量|NIC_USED:"${NIC_USED}'), 'E', 'Linux系统网络流量统计');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (900, 'IBMAIX系统CPU使用率', 'SHELL', concat('#!/bin/sh' , char(10) , '' , char(10) , 'CPU_IDLE_PERCENT=`vmstat 1 2| tail -n 1 | awk ''{print$16}''`' , char(10) , 'CPU_USED_PERCENT=`expr 100 - $CPU_IDLE_PERCENT`' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}CPU使用率|CPU_USED_PERCENT:"${CPU_USED_PERCENT}'), 'U', 'IBMAIX系统CPU使用率');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (500, 'HPUX进程是否存在', 'SHELL', concat('#!/bin/sh ' , char(10) , 'PROCESS_NAME="$1" ' , char(10) , 'PROCESS_PARM="$2" ' , char(10) , 'COUNT=`ps -exf | grep $PROCESS_NAME | grep aicrm | grep $PROCESS_PARM | grep java | grep -v grep | wc -l`' , char(10) , '' , char(10) , 'FLAG=0' , char(10) , 'if [ $COUNT -gt 0 ]; then' , char(10) , '  FLAG=1' , char(10) , 'fi' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}进程"$PROCESS_NAME"-"$PROCESS_PARM"|EXISTFLAG:"$FLAG'), 'U', '检查UNHPUX上进程是否存在');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (600, 'AIX进程是否存在', 'SHELL', concat('#!/bin/sh ' , char(10) , 'PROCESS_NAME="$1" ' , char(10) , 'PROCESS_PARM="$2" ' , char(10) , 'COUNT=`ps -ef | grep $PROCESS_NAME | grep aiams | grep $PROCESS_PARM | grep java | grep -v grep | wc -l`' , char(10) , '' , char(10) , 'FLAG=0' , char(10) , 'if [ $COUNT -gt 0 ]; then' , char(10) , '  FLAG=1' , char(10) , 'fi' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}进程"$PROCESS_NAME"-"$PROCESS_PARM"|EXISTFLAG:"$FLAG'), 'U', '检查AIX主机上进程是否存在');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (1, 'LINUX系统CPU使用率', 'SHELL', concat('#!/bin/sh' , char(10) , 'CPU_IDLE_PERCENT=`vmstat 1 2| tail -n 1 | awk ''{print$15}''`' , char(10) , 'CPU_USED_PERCENT=`expr 100 - $CPU_IDLE_PERCENT`' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}CPU使用率|CPU_USED_PERCENT:"${CPU_USED_PERCENT}'), 'U', 'LINUX系统CPU使用率');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (2, 'LINUX系统内存使用率', 'SHELL', concat('#!/bin/sh' , char(10) , 'FREE=`cat /proc/meminfo | grep MemFree | awk ''{print$2}''`' , char(10) , 'TOTAL=`cat /proc/meminfo | grep MemTotal | awk ''{print$2}''`' , char(10) , 'BUFFER=`cat /proc/meminfo | grep Buffers | awk ''{print$2}''`' , char(10) , 'CACHED=`cat /proc/meminfo | grep Cached | grep -v SwapCached| awk ''{print$2}''`' , char(10) , 'TMP1=`expr $TOTAL - $FREE - $BUFFER - $CACHED`' , char(10) , 'TMP2=`expr $TMP1 \\* 100`' , char(10) , 'MEM_USED_PERCENT=`expr $TMP2 / $TOTAL`' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}内存使用率|MEM_USED_PERCENT:"${MEM_USED_PERCENT}'), 'U', 'LINUX系统内存使用率');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (1000, 'HPUX系统CPU使用率', 'SHELL', concat('#!/bin/sh' , char(10) , '' , char(10) , 'CPU_IDLE_PERCENT=`vmstat 1 2| tail -n 1 | awk ''{print$18}''`' , char(10) , 'CPU_USED_PERCENT=`expr 100 - $CPU_IDLE_PERCENT`' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}CPU使用率|CPU_USED_PERCENT:"${CPU_USED_PERCENT}'), 'U', 'HPUX系统CPU使用率');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (700, 'LINUX进程是否存在', 'SHELL', concat('#!/bin/sh ' , char(10) , 'PROCESS_NAME="$1" ' , char(10) , 'PROCESS_PARM="$2"  ' , char(10) , 'COUNT=`ps -ef | grep $PROCESS_NAME | grep $PROCESS_PARM | grep java | grep -v grep | wc -l`' , char(10) , '' , char(10) , 'FLAG=0' , char(10) , 'if [ $COUNT -gt 0 ]; then' , char(10) , '  FLAG=1' , char(10) , 'fi' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}进程"$PROCESS_NAME"-"$PROCESS_PARM"|EXISTFLAG:"$FLAG'), 'U', 'LINUX进程是否存在');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (8, 'LINUX的/文件系统使用率', 'SHELL', concat('#!/bin/sh' , char(10) , 'FILE_USER_PERCENT=`df | grep /$ | awk ''{print substr($5,1,length($5)-1)}''`' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}文件系统使用率|FS:"${FILE_USER_PERCENT}'), 'U', 'LINUX的/文件系统使用率');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (1100, 'IBMAIX系统内存使用率', 'SHELL', concat('#!/bin/sh' , char(10) , 'FREE=`vmstat -v | sed -n ''3p;'' | awk ''{print$1}''`' , char(10) , 'NOCOMP=`vmstat -v | sed -n ''10p;'' | awk ''{print$1}''`' , char(10) , 'TOTAL=`vmstat -v | sed -n ''1p;'' | awk ''{print$1}''`' , char(10) , 'TMP1=`expr $TOTAL - $FREE - $NOCOMP`' , char(10) , 'TMP2=`expr $TMP1 \\* 100`' , char(10) , 'MEM_USED_PERCENT=`expr $TMP2 / $TOTAL`' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}内存使用率|MEM_USED_PERCENT:"${MEM_USED_PERCENT}'), 'U', 'IBMAIX系统内存使用率');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (1200, 'HPUX系统内存使用率', 'SHELL', concat('#!/bin/sh' , char(10) , 'TMP_FREE=`vmstat | tail -n 1 | awk ''{print$5}''`' , char(10) , 'TMP_FREE2=`expr $TMP_FREE \\* 4`' , char(10) , 'FREE=`expr $TMP_FREE2 / 1024`' , char(10) , 'TOTAL=`/usr/sbin/swapinfo -tam | grep memory | awk ''{print$2}''`' , char(10) , 'TMP1=`expr $TOTAL - $FREE`' , char(10) , 'TMP2=`expr $TMP1 \\* 100`' , char(10) , 'MEM_USED_PERCENT=`expr $TMP2 / $TOTAL`' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}内存使用率|MEM_USED_PERCENT:"${MEM_USED_PERCENT}'), 'U', 'HPUX系统内存使用率');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (300, 'LINUX系统磁盘IO使用率', 'SHELL', concat('#!/bin/sh' , char(10) , 'IO_USED_PERCENT=`iostat -x | sed ''/^$/d'' | awk ''{if(NR>4)printf $1"~"$12*100"@"}''`' , char(10) , 'echo "NAME:{HOST_NAME}-{IP}磁盘IO使用率|IO_USED_PERCENT:"${IO_USED_PERCENT}'), 'U', 'LINUX系统磁盘IO使用率');
insert into AI_MON_P_EXEC (exec_id, name, e_type, expr, state, remarks)
values (13, 'LINUX的文件系统使用率', 'SHELL', concat('#!/bin/sh' , char(10) , '' , char(10) , 'DIRECTORY_NAME=$1' , char(10) , '' , char(10) , 'if [ ! -x "${DIRECTORY_NAME}" ]; then' , char(10) , '   FILE_USER_PERCENT="指定的目录${DIRECTORY_NAME}权限不够,或不存在!"' , char(10) , '   echo "NAME:{HOST_NAME}-{IP}文件系统使用率|FS:"${FILE_USER_PERCENT}' , char(10) , 'else' , char(10) , '   SYSTEM_PERCENT=`df -m | grep /$ | awk ''{print $2}''`' , char(10) , '   DIRECTORY_SIZE=`du -ms ${DIRECTORY_NAME} | awk ''{print $1}''`' , char(10) , '   FILE_USER_PERCENT=`echo "scale=2; (${DIRECTORY_SIZE}/${SYSTEM_PERCENT}*100)" | bc | awk -F. ''{print $1}''`' , char(10) , '   echo "NAME:{HOST_NAME}-{IP}文件系统使用率|FS:"${FILE_USER_PERCENT}' , char(10) , 'fi'), 'U', 'LINUX的文件系统使用率');
commit;