insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_SCHED_TASK_INTER', 11, 'S', 'AI_SCHED_TASK_INTER$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_DEPLOY_APP_PARAM', 11, 'S', 'AI_DEPLOY_APP_PARAM$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_DEPLOY_APP_TEMPLATE', 11, 'S', 'AI_DEPLOY_APP_TEMPLATE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_DEPLOY_NODE_STRATEGY_RELA', 11, 'S', 'AI_DEPLOY_NODE_STRATEGY_RELA$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_DEPLOY_NODE_VERSION', 11, 'S', 'AI_DEPLOY_NODE_VERSION$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_DEPLOY_STRATEGY', 11, 'S', 'AI_DEPLOY_STRATEGY$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_DEPLOY_VERSION', 11, 'S', 'AI_DEPLOY_VERSION$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_GROUP_HOST_REL', 11, 'S', 'AI_MON_GROUP_HOST_REL$SEQ', 99999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('ABG_MON_HOST_LOG', 11, 'S', 'ABG_MON_HOST_LOG$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('ABG_MON_BUSI_ERR_LOG', 11, 'S', 'ABG_MON_BUSI_LOG$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_SERVER_ROUTE', 11, 'S', 'AI_MON_SERVER_ROUTE$SEQ', 99999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_CUSTOMIZE_PANEL', 11, 'S', 'AI_MON_CUSTOMIZE_PANEL$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_CUSTOMIZE_PANEL_RELATE', 11, 'S', 'AI_MON_CUSTOM_PANEL_RELATE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TASK', 11, 'S', 'CFG_TASK$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TASK_PARAM_DEFINE', 11, 'S', 'CFG_TASK_PARAM_DEFINE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TASK_PARAM_TYPE', 11, 'S', 'CFG_TASK_PARAM_TYPE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TASK_PARAM_VALUE', 11, 'S', 'CFG_TASK_PARAM_VALUE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TASK_TYPE', 11, 'S', 'CFG_TASK_TYPE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TF', 11, 'S', 'CFG_TF$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TF_DTL', 11, 'S', 'CFG_TF_DTL$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TF_MAPPING', 11, 'S', 'CFG_TF_MAPPING$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TF_THREAD', 11, 'S', 'CFG_TF_THREAD$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('TASK_LOG', 11, 'S', 'TASK_LOG$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_P_INFO_FILTER', 11, 'S', 'AI_MON_P_INFO_FILTER$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('BATCH_ID', 11, 'S', 'BATCH_ID$SEQ', 999999999999, null, null, null, 100, 'N', 20, null, null, null, 'N', null, 'N', 100, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_W_SMS', 11, 'S', 'AI_MON_W_SMS$SEQ', 999999999999, null, null, null, 50, 'N', 20, null, null, null, 'N', null, 'N', 50, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('DONE_CODE', 11, 'S', 'DONE_CODE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'Y', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_ATTENTION_PANEL', 11, 'S', 'AI_MON_ATTENTION_PANEL$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_CMD', 11, 'S', 'AI_MON_CMD$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_CMDSET', 11, 'S', 'AI_MON_CMDSET$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_COLGRULE', 11, 'S', 'AI_MON_COLGRULE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_PHYSIC_HOST', 11, 'S', 'AI_MON_PHYSIC_HOST$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_CT_RECORD', 11, 'S', 'AI_MON_CT_RECORD$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_DOMAIN', 11, 'S', 'AI_MON_DOMAIN$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_DOMAIN_RELAT', 11, 'S', 'AI_MON_DOMAIN_RELAT$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_GROUP', 11, 'S', 'AI_MON_GROUP$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_NODE', 11, 'S', 'AI_MON_NODE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_LOG', 11, 'S', 'AI_MON_LOG$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_L_RECORD', 11, 'S', 'AI_MON_L_RECORD$SEQ', 999999999999, null, null, null, 100, 'N', 20, null, null, null, 'N', null, 'Y', 100, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_MEMO', 11, 'S', 'AI_MON_MEMO$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_OPTE_REQUISITION', 11, 'S', 'AI_MON_OPTE_REQUISITION$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_PANEL_RELAT_ENTITY', 11, 'S', 'AI_MON_PANEL_RELAT_ENTITY$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_PARAM_DEFINE', 11, 'S', 'AI_MON_PARAM_DEFINE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_PARAM_VALUES', 11, 'S', 'AI_MON_PARAM_VALUES$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_P_EXEC', 11, 'S', 'AI_MON_P_EXEC$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_P_IMGDATA_RESOLVE', 11, 'S', 'AI_MON_P_IMGDATA_RESOLVE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_P_INFO', 11, 'S', 'AI_MON_P_INFO$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_P_INFO_GROUP', 11, 'S', 'AI_MON_P_INFO_GROUP$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_P_TABLE', 11, 'S', 'AI_MON_P_TABLE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_P_THRESHOLD', 11, 'S', 'AI_MON_P_THRESHOLD$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_P_TIME', 11, 'S', 'AI_MON_P_TIME$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_SERVER', 11, 'S', 'AI_MON_SERVER$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_SET', 11, 'S', 'AI_MON_SET$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_USER', 11, 'S', 'AI_MON_USER$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_USER_GROUP', 11, 'S', 'AI_MON_USER_GROUP$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_USER_GROUP_REL', 11, 'S', 'AI_MON_USER_GROUP_REL$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_USER_GROUP_ROLE_REL', 11, 'S', 'AI_MON_USER_GROUP_ROLE_REL$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_USER_PRI_ENTITY', 11, 'S', 'AI_MON_USER_PRI_ENTITY$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_USER_ROLE', 11, 'S', 'AI_MON_USER_ROLE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_USER_ROLE_ENTITY_REL', 11, 'S', 'AI_MON_USER_ROLE_ENT_REL$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_W_DTL', 11, 'S', 'AI_MON_W_DTL$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_W_PERSON', 11, 'S', 'AI_MON_W_PERSON$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_W_TRIGGER', 11, 'S', 'AI_MON_W_TRIGGER$SEQ', 999999999999, null, null, null, 50, 'N', 20, null, null, null, 'N', null, 'N', 50, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_I18N_RESOURCE', 11, 'S', 'AI_MON_I18N_RESOURCE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_REMOTE', 11, 'S', 'CFG_REMOTE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_REMOTE_HANDLER', 11, 'S', 'CFG_REMOTE_HANDLER$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_SOCKET', 11, 'S', 'CFG_SOCKET$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_SOCKET_ASYN', 11, 'S', 'CFG_SOCKET_ASYN$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_SOCKET_FILTER', 11, 'S', 'CFG_SOCKET_FILTER$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_SOCKET_MAPPING', 11, 'S', 'CFG_SOCKET_MAPPING$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_HOST_CON_MODE', 11, 'S', 'AI_MON_HOST_CON_MODE$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('ABG_MON_BUSI_LOG', 11, 'S', 'ABG_MON_BUSI_LOG$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_HOST_USER', 11, 'S', 'AI_MON_HOST_USER$SEQ', 99999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('ABG_MON_W_TRIGGER', 11, 'S', 'ABG_MON_W_TRIGGER$SEQ', 999999999999, null, null, null, 100, 'N', 20, null, null, null, 'N', null, 'N', 100, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_MASTER_SLAVE_REL', 11, 'S', 'AI_MON_MASTER_SLAVE_REL$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('ABG_MON_L_RECORD', 11, 'S', 'ABG_MON_L_RECORD$SEQ', 999999999999, null, null, null, 100, 'N', 20, null, null, null, 'N', null, 'Y', 100, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_NODE_USER', 11, 'S', 'AI_MON_NODE_USER$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('H_AI_DEPLOY_STRATEGY', 11, 'S', 'H_AI_DEPLOY_STRATEGY$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_USERS', 11, 'S', 'AI_MON_USERS$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
--add
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_APP_RULEST', 11, 'S', 'AI_MON_APP_RULEST$SEQ', 100, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_CMDSET_RELAT', 11, 'S', 'AI_MON_CMDSET_RELAT$SEQ', 100, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_CUSTOMIZE_PANEL_RELATE', 11, 'S', 'AI_MON_CUSTOMIZE_PANEL_RELATE$SEQ', 100, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_DB_ACCT', 11, 'S', 'AI_MON_DB_ACCT$SEQ', 100, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_DB_URL', 11, 'S', 'AI_MON_DB_URL$SEQ', 100, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_IL8N_RESOURCE', 11, 'S', 'AI_MON_IL8N_RESOURCE$SEQ', 100, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_LONG', 11, 'S', 'AI_MON_LONG$SEQ', 100, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_L_RECORD_BUSI_201111', 11, 'S', 'AI_MON_L_RECORD_BUSI_201111$SEQ', 100, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_OPTE_REQUISITON', 11, 'S', 'AI_MON_OPTE_REQUISITON$SEQ', 100, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_STATIC_DATA', 11, 'S', 'AI_MON_STATIC_DATA$SEQ', 100, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_USER_ROLE_ENTITY_REL', 11, 'S', 'AI_MON_USER_ROLE_ENTITY_REL$SEQ', 103, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_DB_ACCT', 11, 'S', 'CFG_DB_ACCT$SEQ', 1, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_DTL', 11, 'S', 'CFG_DTL$SEQ', 1, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_DYNC_TABLE_SPLIT', 11, 'S', 'CFG_DYNC_TABLE_SPLIT$SEQ', 1, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_ID_GENERATOR_WRAPPER', 11, 'S', 'CFG_ID_GENERATOR_WRAPPER$SEQ', 1, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_METHOD_CENTER', 11, 'S', 'CFG_METHOD_CENTER$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_SERVICE_CONTROL', 11, 'S', 'CFG_SERVICE_CONTROL$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TABLE_SPLIT', 11, 'S', 'CFG_TABLE_SPLIT$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_TABLE_SPLIT_MAPPING', 11, 'S', 'CFG_TABLE_SPLIT_MAPPING$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('TMP_HOST', 11, 'S', 'TMP_HOST$SEQ', 999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_DEPLOY_NODE_STRATEGY', 11, 'S', 'AI_DEPLOY_NODE_STRATEGY$SEQ',999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_MON_USER_GRP_ROLE_REL', 11, 'S', 'AI_MON_USER_GRP_ROLE_REL$SEQ',999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('RELOAD_LOG', 11, 'S', 'RELOAD_LOG$SEQ',999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('CFG_ID_GENERATOR', 11, 'S', 'CFG_ID_GENERATOR$SEQ',999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('AI_SCHEDULER_OPERATIONS', 11, 'S', 'AI_SCHEDULER_OPERATIONS$SEQ',999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);
insert into CFG_ID_GENERATOR (table_name, domain_id, generator_type, sequence_name, max_id, start_value, min_value, max_value, increment_value, cycle_flag, cache_size, sequence_create_script, his_table_name, his_sequence_name, his_data_flag, his_max_id, his_donecode_flag, step_by, his_step_by)
values ('ABG_MON_BUSI_ERR_LOG', 11, 'S', 'ABG_MON_BUSI_ERR_LOG$SEQ',999999999999, null, null, null, 1, 'N', 20, null, null, null, 'N', null, 'N', null, null);

commit;